#!/bin/sh

#from Rmpi 0.6-6 by Hao Yu
#
#Rmpi is an R package providing an interface to MPI (Message-Passing Interface) 
#API calls with interactive R slave functionalities. 
#
#Copyright (C) 2014 Hao Yu <hyu@stats.uwo.ca>
#
#******************************************************************************
#Rmpi is free software; you can redistribute it and/or modify it under
#the terms of the GNU General Public License as published by the Free
#Software Foundation; either version 2, or (at your option) any later
#version.

#This program is distributed in the hope that it will be useful, but WITHOUT
#ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#for more details.
#    
#You should have received a copy of the GNU General Public License along with 
#this program; if not, write to the Free Software Foundation, Inc., 59 Temple 
#Place, Suite 330, Boston, MA  02111-1307  USA
#******************************************************************************

/bin/rm -rf ./chm
/bin/rm -rf ./config.*
/bin/rm -rf ./autom4te.cache
/bin/rm -rf src/Makevars
/bin/rm -rf src/*.so src/*.o src/*.d src/*.dll src/*.a src/*.rc src/*.rds src/Makedeps
/bin/rm -rf src-*
